spring.application.name=Ecclesia-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecclesia_db
spring.datasource.username=ecclesia_user
spring.datasource.password=ecclesia_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true